version: '3.8'

networks:
  default:
    name: internal-network
    driver: bridge

services:
  # Used for Products storage
  mongo:
    container_name: shopping-api-mongo
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo/database:/data/db
    ports:
      - ${MONGO_PORT}:27017
    restart: always

  # Used for Cart storage
  redis:
    container_name: shopping-api-redis
    image: redis:6.2.6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    restart: always

  shopping-api:
    container_name: shopping-api
    build: .
    environment:
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - mongo
      - redis
    ports:
      - ${SHOPPING_API_PORT}:80
    restart: always