version: '3.8'

networks:
  default:
    name: internal-network
    driver: bridge

services:
  mongo:
    container_name: k183-mongo
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo/database:/data/db
    ports:
      - ${MONGO_PORT}:27017
    restart: always
