version: '3.8'

networks:
  default:
    name: internal-network
    driver: bridge

services:
  mongo:
    container_name: k183-mongo
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo/database:/data/db
    ports:
      - ${MONGO_PORT}:27017
    restart: always

  api:
    container_name: k183-api
    build: .
    environment:
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
    depends_on:
      - mongo
    ports:
      - ${API_PORT}:80
    restart: always
